stages:
  - build
  - test
  - release-job

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  # script:
  #   - insert build script here
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  # script:
  #   - ./scripts/run-all-tests.sh

release-job:
  # script:
  #   - build for release
  artifacts:
    paths:
      - build/*
  only:
    - devel
    - tags
